name: create-ka-formula

on: [workflow_dispatch]

jobs:
  create-formula:
    name: create-ka-formula binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Generate ka formula for brew
      shell: bash
      run: chmod +x scripts/binaries/create-ka-formula && ./scripts/binaries/create-ka-formula > Formula/ka.rb
    - name: Commit formulas binary
      run: |
        git config --global user.name 'Github create-formula action'
        git config --global user.email '43384430+mdpadberg@users.noreply.github.com'
        git add Formula/ka.rb
        git commit -m "Commit new ka brew formula"
        git push 