name: create-formula

on: [workflow_dispatch]

jobs:
  create-formula:
    name: create-mcf-formula binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Generate mcf formula for brew
      shell: bash
      run: chmod +x scripts/binaries/create-mcf-formula && ./scripts/binaries/create-mcf-formula > Formula/mcf.rb
    - name: Generate keep-awake formula for brew
      shell: bash
      run: chmod +x scripts/binaries/create-keep-awake-formula && ./scripts/binaries/create-keep-awake-formula > Formula/keep-awake.rb
    - name: Commit formulas binary
      run: |
        git config --global user.name 'Github create-formula action'
        git config --global user.email '43384430+mdpadberg@users.noreply.github.com'
        git add Formula/mcf.rb
        git commit -m "Commit new brew formula"
        git push 