name: create-formula

on: [workflow_dispatch]

jobs:
  create-formula:
    name: create-mcf-formula binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Generate mcf formula for brew
      shell: bash
      run: chmod +x scripts/binaries/create-mcf-formula && ./scripts/binaries/create-mcf-formula