name: main

on:
  push:
    paths:
      - 'scripts/src/**'

jobs:
  create_binaries:
    name: create-mcf-formula binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Install Rust with cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
    - name: Build scripts in bin folder
      working-directory: scripts
      run: |
        for file in src/bin/*.rs; do
          prefix='src/bin/'
          suffix='.rs'
          file=${file/#$prefix}
          cargo build --bin ${file/%$suffix} --release
        done
    - name: Copy binaries to binaries folder
      shell: bash
      continue-on-error: true
      run: |
        rm scripts/target/release/*.d
        cp scripts/target/release/* scripts/binaries
    - name: Commit create-mcf-formula binary
      run: |
        git config --global user.name 'Github main action'
        git config --global user.email '43384430+mdpadberg@users.noreply.github.com'
        git add scripts/binaries/
        git commit -m "Commit new formula binary"
        git push 