name: main

on:
  push:
    paths:
      - 'scripts/src/**'

jobs:
  create_binaries:
    name: create-mcf-formula binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Install Rust with cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
    - name: Build
      working-directory: scripts
      run: cargo build --bin create-mcf-formula --release
    - name: Copy create-mcf-formula binary to binaries folder
      shell: bash
      run: cp scripts/target/release/create-mcf-formula scripts/binaries 
    - name: Commit create-mcf-formula binary
      run: |
        git config --global user.name 'Github main action'
        git config --global user.email '43384430+mdpadberg@users.noreply.github.com'
        git add scripts/binaries/create-mcf-formula
        git commit -m "Commit new create-mcf-formula binary"
        git push 